version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

  server:
    build: ./backend
    image: server
    container_name: server
    ports: -'4000:4000'

  react:
    build: ./frontend
    image: react
    container_name: react
    ports: -'3000:3000'
