services:
  seed:
    build: ./seed
    container_name: seed
    env_file:
      - ./seed/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/logistica
    networks:
      - backend_proxy

networks:
  backend_proxy:
    external: true
    name: backend_network
