version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

  seed:
    build: ./seed
    image: seed
    container_name: seed
    env_file:
      - ./seed/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/logistica
    depends_on:
      - mongo

  server:
    build: ./backend
    image: server
    container_name: server
    env_file:
      - ./backend/.env.production
    environment:
      - MONGO_URI=mongodb://mongo:27017/logistica
      - REDIS_HOST=redis://redis:6379
      - PORT=4000
    ports:
      - '4000:4000'
    depends_on:
      - mongo
      - redis
      - seed
