services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    networks:
      - backend

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    networks:
      - backend

  server:
    build: ./backend
    image: server
    container_name: server
    env_file:
      - ./backend/.env.production
    environment:
      - MONGO_URI=mongodb://mongo:27017/logistica
      - REDIS_HOST=redis://redis:6379
      - PORT=4000
    ports:
      - '4000:4000'
    depends_on:
      - mongo
      - redis
    networks:
      - backend

networks:
  backend:
    name: backend_network
    driver: bridge

volumes:
  mongodata:
  redisdata:
